// <auto-generated />
using CatBreed.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatBreed.Migrations
{
    [DbContext(typeof(CatBreedContext))]
    [Migration("20230817172650_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CatBreed.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AvgKittenPrice")
                        .HasColumnType("int");

                    b.Property<string>("BreedName")
                        .HasColumnType("longtext");

                    b.Property<string>("Fur")
                        .HasColumnType("longtext");

                    b.Property<string>("Temperament")
                        .HasColumnType("longtext");

                    b.Property<int>("UsPopularity")
                        .HasColumnType("int");

                    b.HasKey("CatId");

                    b.ToTable("Cats");
                });
#pragma warning restore 612, 618
        }
    }
}
